services:
  # Static Site deployment (recommended for Vite apps)
  - type: web
    name: privacy-sentinel
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./privacy-sentinel/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
